code --install-extension christian-kohler.npm-intellisense
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension dbaeumer.vscode-eslint
code --install-extension eg2.tslint
code --install-extension esbenp.prettier-vscode
code --install-extension firefox.scaffold
code --install-extension GrapeCity.gc-excelviewer
code --install-extension Ikuyadeu.r
code --install-extension jchannon.csharpextensions
code --install-extension jithurjacob.nbpreviewer
code --install-extension jmrog.vscode-nuget-package-manager
code --install-extension julielerman.efcore-snippets
code --install-extension k--kato.docomment
code --install-extension Kelvin.vscode-sshfs
code --install-extension Keno.uikit-3-snippets
code --install-extension ms-azuretools.vscode-azureappservice
code --install-extension ms-edgedevtools.vscode-edge-devtools
code --install-extension ms-mssql.mssql
code --install-extension ms-mssql.sqlops-debug
code --install-extension ms-python.python
code --install-extension ms-vscode.azure-account
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.csharp
code --install-extension ms-vsliveshare.vsliveshare
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension octref.vetur
code --install-extension rahulsahay.Csharp-ASPNETCore
code --install-extension robinbentley.sass-indented
code --install-extension schneiderpat.aspnet-helper
code --install-extension sdras.night-owl
code --install-extension sdras.vue-vscode-extensionpack
code --install-extension sdras.vue-vscode-snippets
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension sourcegraph.javascript-typescript
code --install-extension sverrisson-ruv.touchbar-commands
code --install-extension temilaj.asp-net-core-vs-code-extension-pack
code --install-extension tombonnike.vscode-status-bar-format-toggle
code --install-extension vsciot-vscode.vscode-arduino
code --install-extension xabikos.JavaScriptSnippets
code --install-extension yzane.markdown-pdf